### ISSUE TITLE
Important Message

### ISSUE THREAD

**Issue by Zzyzx-Wolfe** [tjhorner/hla-when#2]
Line 16 is wrong in https://github.com/tjhorner/hla-when/blob/master/countdown.js. Please fix.

**Comment by tjhorner** [comment]
PRs welcome

**Comment by Zzyzx-Wolfe** [comment]
> PRs welcome

Sorry, I'm in AZ.

**Comment by tjhorner** [comment]
I guess you'll have to move

**Comment by Zzyzx-Wolfe** [comment]
Hello, I have moved in to your repository. It is quite comfortable.
https://github.com/tjhorner/hla-when/pull/3
